In [1]:
import os
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [17]:
df_tm = pd.read_csv('../data/raw/ThermoADR/SM-29-06-21.csv', skiprows=24)
df_simaj = pd.read_csv('../data/raw/simaj/SantaFeReport1_29jun-23jul2021.csv')

In [19]:
df_tm.rename(columns={'':'PM10','record':'temperatura','Temp':'AtmoPressure','"ug/m3"':'RH','AtmoPressure':'time','Flags':'date'})

,,temperatura,"""ug/m3""",Temp,RHumidity,AtmoPressure,Flags
1,6.81,26.9,47,634.0,2.0,14:09:57,29-jun-2021
2,3.52,27.0,47,634.0,3.0,14:10:57,29-jun-2021
3,1.28,27.1,46,634.0,2.0,14:11:57,29-jun-2021
4,-1.06,27.2,46,634.0,2.0,14:12:57,29-jun-2021
5,-3.19,27.3,45,634.0,2.0,14:13:57,29-jun-2021
...,...,...,...,...,...,...,...
34494,28.27,28.1,45,640.0,2.0,13:02:57,23-jul-2021
34495,58.32,28.1,46,640.0,2.0,13:03:57,23-jul-2021
34496,65.35,28.1,45,640.0,3.0,13:04:57,23-jul-2021
34497,36.46,28.1,45,640.0,3.0,13:05:57,23-jul-2021
34498,27.56,28.1,45,640.0,42.0,13:06:57,23-jul-2021